---
title: "Projects Home Page"
---

I'll keep a list of my little projects here.

## Textbook Notes

Notes on Richard McElreath's "Statistical Rethinking":  
[Link to notes](https://jake-lawler.github.io/rethinking/)  
Chapter summaries, questions answered, plots recreated in tidyverse etc.  

Much less comprehensive notes on "Statistics" by David Freedman, Robert Pisani, and Roger Purves:  
[Link to notes](https://jake-lawler.github.io/Statistics-FPP/)  
Just brief chapter summaries, no answers to questions or similar.

Scattered notes, plots, and a couple of animations from my read through of "Statistical Inference" by George Casella and Roger Berger:  
[Link to notes](https://jake-lawler.github.io/StatisticalInference/)  
Still fairly early on with these. Even after my first full work-through I think I'll be revisiting and adding to these notes for a while.

I'm creating notes on the probabalistic programming language Stan using my read-through of "Regression and Other Stories" by Gelman, Hill & Vehtari as a framework. My notes will not be very related to the book, but will use some of the data and models in the book as a jumping off point as I try to improve my Stan coding. 
The idea is that I'll start by writing very simple Stan models, recreating the earliest models in the book. As the book progresses, I'll need to write more and more complex Stan models to keep up. 
Only just started, here are my notes:  
[Link to notes](https://jake-lawler.github.io/StanNotes/).

Notes on "SQL for Data Scientists" by Renée M. P. Teate are [here](https://jake-lawler.github.io/SQLforDataScientists/).







